server:
  port: 8888

spring:
  application:
    name: springboot-dev

  jpa:
    show-sql: true  # 전송 쿼리 확인
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

jwt:
  issuer: red0808@naver.com
  secret_key: study-springboot